### ISSUE TITLE
Triggers and vibrations on Oculus Touch

### ISSUE THREAD

**Issue by ccarderr** [Kylon99/AlternativePlay#1]
Some bugs i found, that make this mod unplayable for me right now.

1) Trigger button on Oculus Touch. When playing Darth Maul mode with saber split function enabled, sabers split when i touch the trigger instead of pressing it.

2) Controller vibrations when "one color" is enabled. When i cut blocks with left controller, right controller vibrates instead of the left one.

Also i think that when playing with "one color", left saber color and it's trail should be changed to the same as the right one to avoid confusion.

Edit: Not sure if that's important , I'm playing Steam version of the game via Oculus SDK (-vrmode oculus) instead of SteamVR.

**Comment by Kylon99** [comment]
Hello, thanks for the input.  
1.  Do you have to use the split functionality as you can just turn it off for now.  The auto-detect feature was removed since after a SteamVR update it made it only work like 50% of the time.  So I changed it to a dual trigger pull for two controller mode but that may not be feasible for one controller so it was at least offered with one.  I have some ideas about how to solve this but it would take a very long time to code.  (UI for selecting which button you want.)  You can also use SteamVR bindings or OpenVRInputEmulator to map the trigger to a different button temporarily.

2.  Yes, unfortunately the haptic feedback code used some kernel32.dll functions to hook into it and that's very bad going forward with MOD development in general.  I'm looking to restore it somehow but it'll take some time.

EDIT:  Oh plus I don't see any way for me to control the sensitivity of the trigger so far.  All I get to do is detect the button press and Unity has decided the most sensitive press will trigger my code it seems.

Thanks!

**Comment by Kylon99** [comment]
The haptic feedback has been fixed as of version 0.2.2!  The trigger sensitivity can't be fixed though there may be a way to code around it that will take some time to finish.  Thanks.
