### ISSUE TITLE
How does scoring work with this mod?

### ISSUE THREAD

**Issue by WentTheFox** [Kylon99/AlternativePlay#76]
I received a bug report related to this mod on another mod I took over the maintenance of: https://github.com/DJDavid98/BSDataPuller/issues/7

It seems like (at least on the the Darth Maul mode) scoring is changed by this mod from what the game normally provides. Forgive me for my lack of C# knowledge but I could not find what part of this mod is doing this, the calculations DataPuller uses to get the score work well for regular play, and I'm wondering whether there's something I'm missing or this mod is simply not changing the specific part of the code execution that is calculating the good cut score:

https://github.com/DJDavid98/BSDataPuller/blob/ba5c0323a437e991a913df49b4801eb6e803fe43/Harmony/BeatmapObjectExecutionRatingsRecorder.cs#L25

**Comment by Kylon99** [comment]
This mod doesn't touch the scoring calculations.  All it does is if any of the Game Modifiers are enabled it will disable scoring submission.
https://github.com/Kylon99/AlternativePlay/blob/master/AlternativePlay/GameModifiersBehavior.cs
```
BS_Utils.Gameplay.ScoreSubmission.DisableSubmission(AlternativePlay.assemblyName);
```

For the play modes like Darth Maul, Spear, Flail, Nunchaku and the like no scoring changes are made, and scoring is not disabled.  This is because it actually makes the game harder so I left it, especially with the Japanese side that has a league for these modes.

**Comment by WentTheFox** [comment]
I see, thank you!
